### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jcano** [JFTechnology/ember-keycloak-auth#1]
Hey there! 

Amazing project you are starting! I'm trying to use it on my setup and while I'm making some progress, it's a bit frustrating as I have no clue how to use it and it's a long process of trial an error. 

Would it be possible to add a few lines on how to set it up? A couple of examples from your code would be enough, no need for a long list of properties at the moment.

Thanks!

**Comment by sbflynn** [comment]
Hi, and thanks. Yes it is very short (as in devoid) of docs etc. Put it out a little earlier than I had planned in response to a query on the Ember forum.

I will try and add a code example or two over the next day or so - but the general concept is quite simple : init the service (for example in the ‘beforeModel’ hook on the application route) and then use the route and adapter mixins to ensure that you always have a fresh access token whenever you transition to a ‘protected’ route or make an ember-data call to your back-end service. The adapter mixin will then automatically insert the fresh access token into any call to your back-end.

will drop you a line as soon as I have had the chance to add to the documentation.

best gds,

Steve F.

**Comment by sbflynn** [comment]
@jcano took a few days longer than intended as got knocked sideways somewhat by Brexit

1.0.5 has a bit more explanatory text plus a bugfix to the dummy app contributed by @gcusnieux.

All feedback welcome
