### ISSUE TITLE
infinite loop.

### ISSUE THREAD

**Issue by akhedrane** [JFTechnology/ember-keycloak-auth#6]
there is an infinite loop when direct access to protected route.

**Comment by akhedrane** [comment]
i think initializing keycloak should be in beforeModel
and should return keycloak init Promise object to force the router wait initialization.

**Comment by royk** [comment]
I ran into the same problem and the suggested fix worked for me.

**Comment by sbflynn** [comment]
Been swamped - apologies for the delay in applying this.

**Comment by sbflynn** [comment]
Included in v0.1.9
